Running for repo /
Usage: main [OPTIONS] PYPI_NAME

Error: Invalid credentials for GitHub REST API.
